### ISSUE TITLE
Current directory command line option -o c doesn't seem to be implemented. 

### ISSUE THREAD

**Issue by ralesi** [vincpa/z#15]
Looking at the source, I cannot see where the CurrentDirectory option is implemented, nor when I run the `z -o c` does it exclude directory paths outside of my current directory.  I have a patch I can submit getting this to work if interested.

**Comment by vincpa** [comment]
Sure thing. Pull request away.

**Comment by ralesi** [comment]
This should be able to be closed once develop merges to master.

**Comment by vincpa** [comment]
When issuing the z command with the clean parameter and there are no directories for cleaning, it generates the following error

System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.
at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by vincpa** [comment]
Enhancement is now part of the latest release.
