### ISSUE TITLE
Exception when cd-ing

### ISSUE THREAD

**Issue by bwets** [vincpa/z#34]
I get this when I cd to a folder:

System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

It comes from z as it does not happens when the module is not loaded. 
It also started recently, even after updating to latest 1.1.19.

I should note that it happens on Windows 10 Fall Creators Update build 16299.15

Any idea?

**Comment by vincpa** [comment]
Is this any folder? Can you please give me the example of folder name.

**Comment by bwets** [comment]
any folder like c:\Windows. Rooted or not is the sane

**Comment by vincpa** [comment]
Can you please send me your z.psm1 file? I'd like to try it.

**Comment by bwets** [comment]
here it is, renamed to .txt
[z.txt](https://github.com/vincpa/z/files/1361791/z.txt)

**Comment by vincpa** [comment]
Thank you so much for helping me out here. Can you please try the attached file?
[z.txt](https://github.com/vincpa/z/files/1361843/z.txt)

Also can you please provide me with a list of modules which you currently have loaded? You can get this by running `Get-Module`

**Comment by bwets** [comment]
nope, still not ok

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...
Script     1.1.9      z                                   {cdX, popdX, pushdX, z}

**Comment by vincpa** [comment]
Also you said this happened recently, was this previously working?

**Comment by bwets** [comment]
yes it was working like a week ago

**Comment by vincpa** [comment]
One last request, would it at all be possible to send me your .cdHistory file? If that's too sensitive then I'll need to try another approach.

I've also attached a ps1 file which you can load up in PowerShell ISE and run. It will try to CD into C:\Windows. Hopefully it will tell you the line it's failing at.

[z.ps1.txt](https://github.com/vincpa/z/files/1361879/z.ps1.txt)

**Comment by bwets** [comment]
ok, I see that the exception happens when saving the history
My jump-location is huge, because it has detected all subfolders from a git root
It is like 600k and is being written constantly. 
I guess you could ignore .git folders when inspecting a folder structure...

**Comment by vincpa** [comment]
That is bizarre. Thank you for taking the time to help me on this.

**Comment by bwets** [comment]
Well, thank you for trying to fix the problem. I will keep you informed if there is anything new on this.

**Comment by nzbart** [comment]
This issue is now happening to me. Should I open a new issue?

**Comment by vincpa** [comment]
Would it be too much trouble to send me your history file via e-mail? I suspect it's something to do in their. 

Also could you tell me which OS and version you are using as well as the language it's running under?

Thanks

**Comment by nzbart** [comment]
No problem; would I send it to p***e@gmail.com?

I'm running Windows 10.0.16299.309. More info:

```
PS> $host


Name             : ConsoleHost
Version          : 5.1.16299.251
InstanceId       : b20f45e7-bf9f-4edf-b883-302b4d7f2280
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-NZ
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by nzbart** [comment]
Did you receive the file that I sent?

**Comment by vincpa** [comment]
File received thanks. Looks like there's nothing out of the ordinary going on.

I really don't know what the issue is. Your file is not corrupted in anyway.

I suggest you delete your .cdHistory file and launch a powershell session again. If that doesn't work, you might need to assist me in debugging :)

**Comment by nzbart** [comment]
Hi @vincpa ,

I deleted the `.cdHistory` file and opened a new PowerShell window. It appears to be working now. I'll let you know if it stops working again.

Thanks!

**Comment by vincpa** [comment]
I wonder if this has something to do with file permissions. 

Thanks for your time guys.
